changes

diff --git a/source/usr/local/emhttp/plugins/mergerfsp/event/stopping_svcs b/source/usr/local/emhttp/plugins/mergerfsp/event/stopping_svcs
--- a/source/usr/local/emhttp/plugins/mergerfsp/event/stopping_svcs
+++ b/source/usr/local/emhttp/plugins/mergerfsp/event/stopping_svcs
@@ -1,6 +1,23 @@
 #!/bin/bash
 
+CONFIG="/boot/config/plugins/mergerfsp/mergerfsp.cfg"
+[ -e "$CONFIG" ] && source $CONFIG
+
+TIMERSTOPKILL=$((TIMERSTOP+10))
+
 if [ -x /etc/mergerfsp/array_stop.sh ]; then
-    echo "Executing mergerFS array stop script (stopping_svcs)..." | logger
-    /etc/mergerfsp/array_stop.sh 2>&1 | logger
+    echo "mergerFS: array_stop.sh is now executing (event: stopping_svcs)..." | logger -t "mergerfsp"
+
+    timeout --kill-after=$TIMERSTOPKILL /etc/mergerfsp/array_stop.sh 2>&1 | logger -t "mergerfsp"
+    CMDRET="${PIPESTATUS[0]}"
+
+    if [ "$CMDRET" -eq 124 ]; then
+        echo "mergerFS error: array_stop.sh has timed out and was stopped with SIGTERM." | logger -t "mergerfsp"
+    elif [ "$CMDRET" -eq 137 ]; then
+        echo "mergerFS error: array_stop.sh has timed out, was unresponsive to SIGTERM and killed with SIGKILL." | logger -t "mergerfsp"
+    elif [ ! "$CMDRET" -eq 0 ]; then
+        echo "mergerFS error: array_stop.sh has returned with a non-zero exit code ($CMDRET)." | logger -t "mergerfsp"
+    else
+        echo "mergerFS: array_stop.sh was executed with success." | logger -t "mergerfsp"
+    fi
 fi
